# Generated by Django 3.0.2 on 2020-01-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200113_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='unread',
            field=models.NullBooleanField(),
        ),
    ]
