# Generated by Django 3.0.2 on 2020-06-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200401_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Declined'), ('U', 'Undecided')], max_length=1),
        ),
    ]
