# Generated by Django 3.0.2 on 2020-01-21 19:05

import cropperjs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200121_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(default='A little about you', max_length=2500),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cropperjs.models.CropperImageField(upload_to=''),
        ),
    ]
