# Generated by Django 3.0.2 on 2020-01-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200121_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(default='Markdown available, preview below.', max_length=2500),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_avatars/blank.png', upload_to='avatars'),
        ),
    ]
