# Generated by Django 3.0.2 on 2020-07-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_dummy_portfolios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(max_length=2500),
        ),
    ]
